from commands.help import FeXoBotcommands as Command

commands:set[Command] = {
    Command("setup",
            "Setup The Server For The Bot",
            "`/setup`",
            "Moderator",
            "Administator",
            "guild only"),
    Command("help",
            "Shows this message",
            "`/help`"),
    Command(
        "warn",
        "Warns a member",
        "`/warn <member> <reason>`",
        "Moderator",
        "Manage Messages",
        "guild only",
    ),
    Command(
        "warns",
        "Shows a user's warns",
        "`/warns <member>`",
        "Moderator",
        "Manage Messages",
        "guild only",
    ),
    Command(
        "clearwarns",
        "Clears a user's warns",
        "`/clearwarns <member>`",
        "Moderator",
        "Manage Messages",
        "guild only",
    ),
    Command(
        "clear",
        "Clears messages",
        "`/clear <amount>`",
        "Moderator",
        "Manage Messages",
        "guild only",
    ),
    Command(
        "kick",
        "Kicks a member",
        "`/kick <member> <reason>`",
        "Moderator",
        "Kick Members",
        "guild only",
    ),
    Command(
        "ban",
        "Bans a member",
        "`/ban <member> <reason>`",
        "Moderator",
        "Ban Members",
        "guild only",
    ),
    Command(
        "mute",
        "Mutes a member",
        "`/mute <member> <reason>`",
        "Moderator",
        "Manage Roles",
        "guild only",
    ),
    Command(
        "announcement",
        "Sends an announcement To the announcement channel",
        "`/announcement <message>`",
        "Moderator",
        "Administrator",
        "guild only",
    ),
    Command(
        "perms",
        "Shows a member's permissions",
        "`/perms <member>`",
        "Moderator",
        "Manage Roles",
        "guild only",
    ),    
    Command(
        "unban",
        "Unbans a member",
        "`/unban <member>`",
        "Moderator",
        "Ban Members",
        "guild only",
    ),
    Command(
        "embed",
        "Creates a custom embed",
        "`/embed`",
        "Moderator",
        "Manage Messages",
        "guild only",
    ),
    Command(
        "giveaway",
        "Starts a giveaway",
        "`/giveaway <prize> <days> <winners> <channel>`",
        "Moderator",
        "Manage Guild",
        "guild only",
    ),
    Command(
        "poll",
        "Creates a poll",
        "`/poll <question> <option1> <option2> <option3> <option4>`",
        "Utility",
        location="guild only",
    ),
    Command(
        "report",
        "Report a message",
        "`/report <message_id>`",
        "Utility",
        location="guild only",
    ),
    Command(
        "ticket",
        "Creates a ticket",
        "`/ticket`",
        "Utility",
        location="guild only",
    ),
    Command(
        "translate",
        "Translate a message to another language.",
        "`/translate <text> <language>`",
        "Utility",        
    ),
    Command(
        "invite",
        "Invite the bot to your server.",
        "`/invite`",
        "Utility",
    ),
    Command(
        "avatar",
        "Get a users avatar.",
        "`/avatar <user>`",
        "Fun",
    ),
    Command(
        "hangman",
        "Play hangman.",
        "`/hangman`",
        "Games",
    ),
    Command(
        "define",
        "Define a word in any language.",
        "`/define <word>`",
        "Utility",
    ),
    Command(
        "joke",
        "Get a joke.",
        "`/joke <type> <category> <lang>`",
        "Fun",
    ),
    Command(
        "chatgpt",
        "Ask ChatGPT a question.",
        "`/chatgpt <message>`",
        "Utility",
    ),
    Command(
        "ping",
        "Get the bot's ping.",
        "`/ping`",
        "Utility",
    ),
    Command(
        "fact",
        "Get a fact.",
        "`/fact`",
        "Fun",
    ),
    Command(
        "level",
        "Get a users level.",
        "`/level <user>`",
        "Fun",
    ),
    Command(
        "translate",
        "Translate a message to another language.",
        "`Used by App Context Menu`",
        "App",
    ),
    Command(
        "report",
        "Report a message.",
        "`Used by App Context Menu`",
        "App",
    ),
    Command(
        "Bookmark",
        "Bookmark a message.",
        "`Used by App Context Menu`",
        "App",
    ),
    Command(
        "Explain GPT",
        "Explain a message Using ChatGPT.",
        "`Used by App Context Menu`",
        "App",
    ),
    Command(
        "8ball",
        "Ask the 8ball a question.",
        "`/8ball <question>`",
        "Fun",
    ),
    Command(
        "coinflip",
        "Flip a coin.",
        "`/coinflip`",
        "Fun",
    ),
    Command(
        "dice",
        "Roll a dice.",
        "`/dice`",
        "Fun",
    ),
    Command(
        "rockpaperscissors",
        "Play rock paper scissors.",
        "`/rockpaperscissors`",
        "Fun",
    ),
    Command(
        "random number",
        "Get a random number.",
        "`/random number <min> <max>`",
        "Fun",
    ),
    Command(
        "random color",
        "Get a random color.",
        "`/random color`",
        "Fun",
    ),
    Command(
        "random choice",
        "Get a random choice.",
        "`/random choice <choices>`",
        "Fun",
    ),
    Command(
        "suggest",
        "Suggest Something To The Bot",
        "`/suggest <title> <description>`",
        "Utility",
    ),
    Command(
        "bug",
        "Report A Bug",
        "`/bug <title> <description>`",
        "Utility",
    ),
    Command(
        "feedback",
        "Give Feedback",
        "`/feedback <title> <description>`",
        "Utility",
    ),
    Command(
        "config",
        "View the bot config of your server.",
        "`/config`",
        "Utility",
    ),
    Command(
        "tinyurl create",
        "Shorten a url.",
        "`/tinyurl create <url> <name>`",
        "Utility",
    ),
    Command(
        "tinyurl stats",
        "Get the stats of a tinyurl.",
        "`/tinyurl stats <alias>`",
        "Utility",
    ),
    Command(
        "tictactoe",
        "Play tic tac toe.",
        "`/tictactoe <opponent>`",
        "Games",
        location="guild only",
    ),
    Command(
        "Encrypt",
        "Encrypt a message.",
        "`Used by App Context Menu`",
        "App",
    ),
    Command(
        "encrypt",
        "Encrypt a message.",
        "`/encrypt <text>`",
        "Utility",
    ),
    Command(
        "decrypt",
        "Decrypt a message.",
        "`/decrypt <text>`",
        "Utility",
    ),
    Command(
        "reactionrole",
        "Create a reaction role.",
        "`/reactionrole <message_id> <emoji> <role> <limit>`",
        "Moderator",
        "Manage Roles",
        "guild only",
    ),
    Command(
        "random password",
        "Generate a password.",
        "`/random password <type> <length>`",
        "Utility",
    ),
    Command(
        "Warn User",
        "Warn a user.",
        "`Used by App Context Menu`",
        "App",
    ),
    Command(
        "afk",
        "Set your status to AFK.",
        "`/afk <status>`",
        "Utility",
    ),
    Command(
        "ascii",
        "Convert text to ascii.",
        "`/ascii <text>`",
        "Utility",
    ),
    Command(
        "sudo",
        "Make someone say something.",
        "`/sudo <member> <message>`",
        "Fun",
    ),
    Command(
        "timer",
        "Create a timer.",
        "`/timer <time> <reason>`",
        "Utility",
    ),
    Command(
        "currency",
        "Convert currency.",
        "`/currency <amount> <from> <to>`",
        "Utility",
    ),
    Command(
        "insult",
        "Insult someone.",
        "`/insult <member>`",
        "Fun",
    ),
    Command(
        "recipe",
        "Get a recipe.",
        "`/recipe <food>`",
        "Utility",
    ),
    Command(
        "tempmail create",
        "Create a temporary email.",
        "`/tempmail create <tag>`",
        "Utility",
    ),
    Command(
        "tempmail inbox",
        "Get the inbox of a temporary email.",
        "`/tempmail inbox <tag>`",
        "Utility",
    ),
    Command(
        "time zone",
        "Get the time of a timezone.",
        "`/time zone <timezone>`",
        "Utility",
    ),
    Command(
        "role add",
        "Add a role to a member.",
        "`/role add <member> <role>`",
        "Moderator",
        "Manage Roles",
        "guild only",
        
    ),
    Command(
        "role remove",
        "Remove a role from a member.",
        "`/role remove <member> <role>`",
        "Moderator",
        "Manage Roles",
        "guild only",
    ),
    Command(
        "role create",
        "Create a role.",
        "`/role create <name> <color> <hoist> <mentionable>`",
        "Moderator",
        "Manage Roles",
        "guild only",
    ),
    Command(
        "role delete",
        "Delete a role.",
        "`/role delete <role>`",
        "Moderator",
        "Manage Roles",
        "guild only",
    ),
    Command(
        "role edit",
        "Edit a role.",
        "`/role edit <role> <name> <color> <hoist> <mentionable>`",
        "Moderator",
        "Manage Roles",
        "guild only",
    ),
    Command(
        "role info",
        "Get info on a role.",
        "`/role info <role>`",
        "Moderator",
        "Manage Roles",
        "guild only",
    ),
    Command(
        "role list",
        "List all roles.",
        "`/role list`",
        "Moderator",
        "Manage Roles",
        "guild only",
    ),
    Command(
        "role permissions",
        "Get the permissions of a role.",
        "`/role permissions <role>`",
        "Moderator",
        "Manage Roles",
        "guild only",
    ),
    Command(
        "role all",
        "Add or remove a role from all members.",
        "`/role all <role> <add/remove>`",
        "Moderator",
        "Manage Roles",
        "guild only",
    ),
    Command(
        "image search",
        "Search for an image.",
        "`/image search <query>`",
        "Utility",
    ),
    Command(
        "math add",
        "Add numbers.",
        "`/math add <x> <y>`",
        "Utility",
    ),
    Command(
        "math subtract",
        "Subtract numbers.",
        "`/math subtract <x> <y>`",
        "Utility",
    ),
    Command(
        "math multiply",
        "Multiply numbers.",
        "`/math multiply <x> <y>`",
        "Utility",
    ),
    Command(
        "math divide",
        "Divide numbers.",
        "`/math divide <x> <y>`",
        "Utility",
    ),
    Command(
        "math calculate",
        "Calculate an expression.",
        "`/math calculate <expression>`",
        "Utility",
    ),
    Command(
        "math calculator",
        "Open a calculator.",
        "`/math calculator`",
        "Utility",
    ),
    Command(
        "math factorial",
        "Get the factorial of a number.",
        "`/math factorial <number>`",
        "Utility",
    ),
    Command(
        "math mean",
        "Get the mean of numbers.",
        "`/math mean <numbers>`",
        "Utility",
    ),
    Command(
        "math median",
        "Get the median of numbers.",
        "`/math median <numbers>`",
        "Utility",
    ),
    Command(
        "math power",
        "Raise a number to a power.",
        "`/math power <base> <exponent>`",
        "Utility",
    ),
    Command(
        "math root",
        "Get the square root of a number.",
        "`/math root <number> <root>`",
        "Utility",
    ),
    Command(
        "math pythagorean",
        "Calculate the pythagorean theorem.",
        "`/math pythagorean <a> <b>`",
        "Utility",
    ),
    Command(
        "math quadratic",
        "Solve a quadratic equation.",
        "`/math quadratic <equation>`",
        "Utility",
    ),
    Command(
        "nasa apod",
        "Get the NASA Astronomy Picture of the Day.",
        "`/nasa apod`",
        "Utility",
    ),
    Command(
        "quote",
        "Get a quote.",
        "`/quote`",
        "Utility",
    ),
    Command(
        "trivia",
        "Play trivia.",
        "`/trivia <category> <difficulty>`",
        "Games",
    ),
    
        
    
    
        
}
def get_commands():
    return commands

commands:list = list(get_commands())
commands.sort(key=lambda x: x.name)
for command in commands:
    print(f"Name: {command.name}\nDescription: {command.description}\nUsage: {command.usage}\nPermissions: {command.required_permission}\nLocation: {command.location}\n")
    

    

