// VoiceMatter Project Data
// Generated by project-sync on 2026-08-26 from projects/VoiceMatter/metadata.json
// Sacred fields (overview.* detail, features[].rich, architecture.services,
// apiEndpoints, setupSteps, knownIssues, futureEnhancements) are TODO — admin
// fills in by hand from projects/VoiceMatter/*.md files.

export const voiceMatterData = {
  // From metadata.json
  title: "VoiceMatter",
  shortDescription: "Press-to-record Linux voice dictation daemon: Deepgram STT + Anthropic-compatible LLM formatter, with a frameless PySide6 overlay and auto-paste via ydotool.",

  github: "https://github.com/KazimFedxD", // metadata.github was empty — fallback used, manual review needed
  liveDemo: "",

  badges: [
    { icon: "Construction", text: "🚧 Alpha — v0.1.0" },
    { icon: "Sparkles", text: "🐧 Linux-only" },
    { icon: "Mic", text: "🎤 Voice-first input" },
    { icon: "Lock", text: "🔒 Local-only control surface" }
  ],

  techStack: [
    { name: "Python", version: "3.11", category: "Backend" },
    { name: "PySide6", version: "6", category: "Frontend" },
    { name: "sounddevice", version: "", category: "External Service" },
    { name: "NumPy", version: "", category: "External Service" },
    { name: "Deepgram Nova-3 SDK", version: "", category: "External Service" },
    { name: "Anthropic SDK", version: "", category: "External Service" },
    { name: "wl-copy", version: "", category: "External Service" },
    { name: "ydotool", version: "", category: "External Service" },
    { name: "PipeWire", version: "", category: "External Service" },
    { name: "WirePlumber", version: "", category: "External Service" },
    { name: "Unix domain sockets", version: "AF_UNIX", category: "External Service" },
    { name: "python-dotenv", version: "", category: "External Service" },
    { name: "uv", version: "", category: "External Service" }
  ],

  awards: [],

  // ============================================================
  // OVERVIEW
  // ============================================================
  overview: {
    description: "VoiceMatter is a Linux desktop daemon that listens when you press a key, transcribes what you said, runs the transcript through an LLM to clean it up, and pastes the polished result into whichever application you're working in. It is a single-user, always-available dictation layer that sits between your microphone and your editor.",
    // TODO: hand-author overview.problemIntro, problemStatement, howWeSolve,
    //       targetAudience, uniqueFeatures, useCases, comparison from projects/VoiceMatter/overview.md

    problemIntro: "",
    problemStatement: [],
    howWeSolve: [],
    targetAudience: [],
    uniqueFeatures: [],
    useCases: [],
    comparison: { traditional: [], voicematter: [] },
  },

  mainFlow: { title: "", subtitle: "", description: "", oneLiner: "", steps: [], corePrinciples: [] },
  // TODO: hand-author from projects/VoiceMatter/overview.md "How It Works" section

  features: [
    {
      id: 1,
      title: "Press-to-record hotkey daemon",
      icon: "Mic",
      description: "KDE-bound F8/F9/Esc survive alt-tab and reboots",
    },
    {
      id: 2,
      title: "Deepgram Nova-3 transcription",
      icon: "Sparkles",
      description: "Fast multi-lingual STT with smart_format",
    },
    {
      id: 3,
      title: "LLM-powered formatter",
      icon: "Brain",
      description: "Editor-not-writer prompt that drops filler + fixes grammar",
    },
    {
      id: 4,
      title: "Auto-copy + auto-paste",
      icon: "Sparkles",
      description: "wl-copy to clipboard, ydotool for synthetic Ctrl+V",
    },
    {
      id: 5,
      title: "Floating PySide6 overlay",
      icon: "Sparkles",
      description: "Frameless pill with live audio meter, 6 visual states",
    },
    {
      id: 6,
      title: "KDE global hotkeys",
      icon: "Sparkles",
      description: "Absolute-path CLI subcommands: trigger / pause / cancel / stop",
    },
  ],
  // TODO: hand-author features[].whyItMatters, howItWorks, codeSnippets from projects/VoiceMatter/features.md

  architecture: {
    description: "", // TODO: extract from projects/VoiceMatter/architecture.md first paragraph
    servicesTitle: "Services",
    servicesIntro: "",
    diagram: { title: "", description: "", layers: [] },
    services: [],
  },
  // TODO: hand-author architecture.diagram and architecture.services from projects/VoiceMatter/architecture.md

  apiEndpoints: [],    // TODO: hand-author from backend code or projects/VoiceMatter/architecture.md
  setupSteps: [],      // TODO: hand-author from projects/VoiceMatter/setup.md
  screenshots: [],     // populated by project-sync via 07-screenshots-sync.md

  performance: {
    pageLoad: [
      { metric: "Page Load Time",    target: "[unmeasured]",                                 actual: "" },
      { metric: "API Response Time", target: "~3-9s end-to-end [estimated]",                  actual: "" },
      { metric: "Bundle Size",        target: "~110 MB RAM [estimated]",                      actual: "" },
    ],
    apiResponseTimes: [],
    webSocketLatency: [],
    lighthouseScores: {
      desktop: { performance: null, accessibility: null, bestPractices: null, seo: null },
      mobile:  { performance: null, accessibility: null, bestPractices: null, seo: null },
    },
    bundleSize: { total: "~110 MB RAM [estimated]", breakdown: [] },
  },

  requirements: {
    os: [
      { name: "Arch Linux",     supported: true },
      { name: "Fedora",         supported: true, notes: "35+" },
      { name: "Ubuntu",         supported: true, notes: "22.04+" },
      { name: "Debian",         supported: true, notes: "12+" },
      { name: "KDE neon",       supported: true },
    ],
    hardware: {
      minimum:    { ram: "2 GB",       cpu: "Dual-core 2GHz+", disk: "200 MB free" },
      recommended: { ram: "4 GB",       cpu: "Quad-core 2.5GHz+", disk: "500 MB free" },
    },
    software: [
      { name: "Python",         version: "3.11+",     required: true, purpose: "Runtime" },
      { name: "uv",             version: "0.4+",      required: true, purpose: "Package manager" },
      { name: "PipeWire",       version: "0.3.50+",   required: true, purpose: "Audio capture" },
      { name: "WirePlumber",    version: "0.4+",      required: true, purpose: "Audio session manager" },
      { name: "wl-clipboard",   version: "2.0+",      required: true, purpose: "Wayland clipboard" },
      { name: "ydotool",        version: "1.6+",      required: false, purpose: "Synthetic input" },
    ],
    browsers: [],
    externalServices: [
      { name: "Deepgram API key",                        purpose: "Nova-3 speech-to-text",                 freeTier: false },
      { name: "Anthropic-API-compatible LLM endpoint",    purpose: "Transcript formatting",                  freeTier: false },
    ],
  },

  knownIssues: [],          // TODO: hand-author from projects/VoiceMatter/known-issues.md
  futureEnhancements: [],   // TODO: hand-author from projects/VoiceMatter/future.md
  relatedProjects: [],      // TODO: hand-curate from cross-references
};